import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:flutter_secure_storage/flutter_secure_storage.dart';

void main() => runApp(const SecureTradeApp());

class ApiClient {
  ApiClient(this.baseUrl);
  final String baseUrl;
  final _storage = const FlutterSecureStorage();
  Future<List<dynamic>> markets() async { final r=await http.get(Uri.parse('$baseUrl/api/v1/markets')); if(r.statusCode!=200) throw Exception('Unable to load markets'); return jsonDecode(r.body)['data']; }
  Future<List<dynamic>> ads() async { final r=await http.get(Uri.parse('$baseUrl/api/v1/p2p/ads')); if(r.statusCode!=200) throw Exception('Unable to load P2P offers'); return jsonDecode(r.body)['data']; }
}

class SecureTradeApp extends StatelessWidget { const SecureTradeApp({super.key}); @override Widget build(BuildContext context)=>MaterialApp(title:'SecureTrade',debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const HomeScreen()); }
class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen> { final api=ApiClient('http://10.0.2.2:4000'); int index=0; @override Widget build(BuildContext context){final pages=[const Dashboard(), FuturePanel(title:'Markets',loader:api.markets,item:(x)=>'${x['symbol']}'), FuturePanel(title:'P2P Marketplace',loader:api.ads,item:(x)=>'${x['assetSymbol']}/${x['fiatCode']} • ${x['price']}'), const WalletScreen(), const ProfileScreen()]; return Scaffold(appBar:AppBar(title:const Text('SecureTrade'),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none))]),body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(i)=>setState(()=>index=i),destinations:const[NavigationDestination(icon:Icon(Icons.dashboard_outlined),label:'Home'),NavigationDestination(icon:Icon(Icons.show_chart),label:'Markets'),NavigationDestination(icon:Icon(Icons.swap_horizontal_circle_outlined),label:'P2P'),NavigationDestination(icon:Icon(Icons.account_balance_wallet_outlined),label:'Wallet'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Profile')]),);}}
class Dashboard extends StatelessWidget { const Dashboard({super.key}); @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:[Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Portfolio Value',style:TextStyle(fontSize:14)),const SizedBox(height:8),Text('₹ 0.00',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:16),Row(children:[Expanded(child:FilledButton(onPressed:(){},child:const Text('Deposit'))),const SizedBox(width:10),Expanded(child:OutlinedButton(onPressed:(){},child:const Text('Withdraw')))])])),),const SizedBox(height:12),const Text('Quick actions',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold)),const SizedBox(height:8),Wrap(spacing:10,runSpacing:10,children:['Buy Crypto','Sell Crypto','Spot Trading','P2P Trading','Transactions','Security'].map((x)=>ActionChip(label:Text(x),onPressed:(){})).toList()),]); }
class FuturePanel extends StatelessWidget { const FuturePanel({super.key,required this.title,required this.loader,required this.item}); final String title; final Future<List<dynamic>> Function() loader; final String Function(dynamic) item; @override Widget build(BuildContext context)=>FutureBuilder<List<dynamic>>(future:loader(),builder:(c,s){if(s.connectionState!=ConnectionState.done)return const Center(child:CircularProgressIndicator());if(s.hasError)return Center(child:Text('Unable to load $title'));final data=s.data??[];return ListView(padding:const EdgeInsets.all(12),children:[Text(title,style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),...data.map((x)=>Card(child:ListTile(title:Text(item(x)),subtitle:Text('Live platform data'),trailing:const Icon(Icons.chevron_right))))]);});}
class WalletScreen extends StatelessWidget { const WalletScreen({super.key}); @override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(16),children:const[Text('Wallet',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),SizedBox(height:16),ListTile(leading:Icon(Icons.currency_bitcoin),title:Text('BTC'),subtitle:Text('Available 0.00000000'),trailing:Text('₹ 0.00')),ListTile(leading:Icon(Icons.token),title:Text('USDT'),subtitle:Text('Available 0.00'),trailing:Text('₹ 0.00'))]);}
class ProfileScreen extends StatelessWidget { const ProfileScreen({super.key}); @override Widget build(BuildContext context)=>ListView(children:const[ListTile(leading:Icon(Icons.verified_user_outlined),title:Text('KYC & Verification'),trailing:Icon(Icons.chevron_right)),ListTile(leading:Icon(Icons.security),title:Text('Security & 2FA'),trailing:Icon(Icons.chevron_right)),ListTile(leading:Icon(Icons.devices),title:Text('Devices & Sessions'),trailing:Icon(Icons.chevron_right)),ListTile(leading:Icon(Icons.support_agent),title:Text('Support'),trailing:Icon(Icons.chevron_right))]);}
