import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { z } from 'zod';
import { PrismaClient, UserRole, UserStatus, OrderSide, OrderType, P2PStatus, LedgerDirection } from '@prisma/client';

const prisma = new PrismaClient();
const app = express();
app.use(helmet());
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(',') ?? true, credentials: true }));
app.use(express.json({ limit: '1mb' }));

const JWT_SECRET = process.env.JWT_SECRET ?? 'development-only-change-me';
const sign = (user: {id:string; role:UserRole}) => jwt.sign({ sub:user.id, role:user.role }, JWT_SECRET, { expiresIn: (process.env.JWT_EXPIRES_IN ?? '15m') as jwt.SignOptions['expiresIn'] });

type AuthReq = express.Request & { auth?: {id:string; role:UserRole} };
const auth = (req:AuthReq,res:express.Response,next:express.NextFunction) => { try { const token=req.headers.authorization?.replace('Bearer ',''); if(!token) return res.status(401).json({success:false,code:'UNAUTHORIZED'}); const payload=jwt.verify(token,JWT_SECRET) as jwt.JwtPayload & {role:UserRole}; if(!payload.sub) return res.status(401).json({success:false,code:'INVALID_TOKEN'}); req.auth={id:payload.sub,role:payload.role}; next(); } catch { return res.status(401).json({success:false,code:'INVALID_TOKEN'}); } };
const roles = (...allowed:UserRole[]) => (req:AuthReq,res:express.Response,next:express.NextFunction) => { if(!req.auth || !allowed.includes(req.auth.role)) return res.status(403).json({success:false,code:'FORBIDDEN'}); next(); };
const audit = async (actorId:string|undefined, action:string, entityType:string, entityId:string|undefined, reason:string|undefined, req:express.Request) => prisma.auditLog.create({data:{actorId,action,entityType,entityId,reason,ip:req.ip,requestId:req.header('x-request-id') ?? undefined}});

app.get('/health', (_req,res)=>res.json({success:true,service:'securetrade-api',time:new Date().toISOString()}));

app.post('/api/v1/auth/register', async (req,res,next)=>{ try { const input=z.object({email:z.string().email(),password:z.string().min(10),phone:z.string().optional(),fullName:z.string().min(2).optional()}).parse(req.body); const exists=await prisma.user.findUnique({where:{email:input.email.toLowerCase()}}); if(exists) return res.status(409).json({success:false,code:'EMAIL_EXISTS'}); const passwordHash=await bcrypt.hash(input.password,12); const user=await prisma.user.create({data:{email:input.email.toLowerCase(),phone:input.phone,passwordHash,profile:{create:{fullName:input.fullName}}}}); await audit(user.id,'USER_REGISTERED','User',user.id,undefined,req); res.status(201).json({success:true,data:{id:user.id,email:user.email,role:user.role,token:sign(user)}}); } catch(e){next(e)} });
app.post('/api/v1/auth/login', async (req,res,next)=>{ try { const input=z.object({email:z.string().email(),password:z.string()}).parse(req.body); const user=await prisma.user.findUnique({where:{email:input.email.toLowerCase()}}); if(!user || !(await bcrypt.compare(input.password,user.passwordHash))) return res.status(401).json({success:false,code:'INVALID_CREDENTIALS'}); if(user.status!==UserStatus.ACTIVE) return res.status(403).json({success:false,code:'ACCOUNT_RESTRICTED'}); const token=sign(user); await audit(user.id,'USER_LOGIN','User',user.id,undefined,req); res.json({success:true,data:{id:user.id,email:user.email,role:user.role,token}}); } catch(e){next(e)} });

app.get('/api/v1/assets', async (_req,res,next)=>{try{const assets=await prisma.asset.findMany({where:{enabled:true},include:{networks:{include:{network:true}}}});res.json({success:true,data:assets})}catch(e){next(e)}});
app.get('/api/v1/markets', async (_req,res,next)=>{try{const pairs=await prisma.tradingPair.findMany({where:{enabled:true},include:{baseAsset:true,quoteAsset:true}});res.json({success:true,data:pairs})}catch(e){next(e)}});
app.get('/api/v1/p2p/ads', async (req,res,next)=>{try{const q=z.object({asset:z.string().optional(),fiat:z.string().optional(),side:z.enum(['BUY','SELL']).optional()}).parse(req.query);const ads=await prisma.p2PAdvertisement.findMany({where:{active:true,assetSymbol:q.asset,fiatCode:q.fiat,side:q.side as OrderSide|undefined},include:{vendor:{select:{id:true,email:true,kycStatus:true}}},orderBy:{createdAt:'desc'}});res.json({success:true,data:ads})}catch(e){next(e)}});

app.get('/api/v1/me',auth,async(req:AuthReq,res,next)=>{try{const user=await prisma.user.findUnique({where:{id:req.auth!.id},include:{profile:true,wallets:{include:{asset:true}}}});res.json({success:true,data:user})}catch(e){next(e)}});
app.get('/api/v1/admin/audit',auth,roles(UserRole.SUPER_ADMIN,UserRole.AUDITOR),async(_req,res,next)=>{try{const logs=await prisma.auditLog.findMany({orderBy:{createdAt:'desc'},take:200,include:{actor:{select:{id:true,email:true,role:true}}}});res.json({success:true,data:logs})}catch(e){next(e)}});

app.post('/api/v1/vendor/ads',auth,roles(UserRole.USER,UserRole.VENDOR),async(req:AuthReq,res,next)=>{try{const input=z.object({assetSymbol:z.string().min(2),fiatCode:z.string().length(3),side:z.enum(['BUY','SELL']),price:z.coerce.number().positive(),available:z.coerce.number().positive(),minOrder:z.coerce.number().positive(),maxOrder:z.coerce.number().positive(),paymentMethod:z.string().min(2),terms:z.string().max(2000).optional()}).parse(req.body);const ad=await prisma.p2PAdvertisement.create({data:{vendorId:req.auth!.id,...input,side:input.side as OrderSide,price:input.price,available:input.available,minOrder:input.minOrder,maxOrder:input.maxOrder}});await audit(req.auth!.id,'P2P_AD_CREATED','P2PAdvertisement',ad.id,undefined,req);res.status(201).json({success:true,data:ad})}catch(e){next(e)}});

app.post('/api/v1/p2p/orders',auth,async(req:AuthReq,res,next)=>{try{const input=z.object({advertisementId:z.string(),cryptoAmount:z.coerce.number().positive()}).parse(req.body);const ad=await prisma.p2PAdvertisement.findUnique({where:{id:input.advertisementId}});if(!ad||!ad.active)return res.status(404).json({success:false,code:'AD_NOT_FOUND'});if(input.cryptoAmount<Number(ad.minOrder)||input.cryptoAmount>Number(ad.maxOrder)||input.cryptoAmount>Number(ad.available))return res.status(400).json({success:false,code:'AMOUNT_OUT_OF_RANGE'});if(ad.vendorId===req.auth!.id)return res.status(400).json({success:false,code:'SELF_ORDER'});const order=await prisma.p2POrder.create({data:{advertisementId:ad.id,buyerId:req.auth!.id,sellerId:ad.vendorId,assetSymbol:ad.assetSymbol,fiatCode:ad.fiatCode,cryptoAmount:input.cryptoAmount,fiatAmount:input.cryptoAmount*Number(ad.price),status:P2PStatus.CREATED}});await audit(req.auth!.id,'P2P_ORDER_CREATED','P2POrder',order.id,undefined,req);res.status(201).json({success:true,data:order})}catch(e){next(e)}});

app.post('/api/v1/p2p/orders/:id/escrow',auth,async(req:AuthReq,res,next)=>{try{const order=await prisma.p2POrder.findUnique({where:{id:(req.params.id as string)}});if(!order)return res.status(404).json({success:false,code:'ORDER_NOT_FOUND'});if(order.sellerId!==req.auth!.id)return res.status(403).json({success:false,code:'FORBIDDEN'});if(order.status!==P2PStatus.CREATED)return res.status(409).json({success:false,code:'INVALID_STATUS'});const updated=await prisma.$transaction(async tx=>{const escrow=await tx.escrow.create({data:{p2pOrderId:order.id,assetSymbol:order.assetSymbol,amount:order.cryptoAmount}});const o=await tx.p2POrder.update({where:{id:order.id},data:{status:P2PStatus.ESCROW_LOCKED}});return {o,escrow}});await audit(req.auth!.id,'P2P_ESCROW_LOCKED','P2POrder',order.id,'Seller locked crypto for escrow',req);res.json({success:true,data:updated})}catch(e){next(e)}});

app.post('/api/v1/p2p/orders/:id/payment-sent',auth,async(req:AuthReq,res,next)=>{try{const order=await prisma.p2POrder.findUnique({where:{id:(req.params.id as string)}});if(!order||order.buyerId!==req.auth!.id)return res.status(404).json({success:false,code:'ORDER_NOT_FOUND'});if(order.status!==P2PStatus.ESCROW_LOCKED)return res.status(409).json({success:false,code:'INVALID_STATUS'});const o=await prisma.p2POrder.update({where:{id:order.id},data:{status:P2PStatus.PAYMENT_SENT}});await audit(req.auth!.id,'P2P_PAYMENT_MARKED_SENT','P2POrder',o.id,undefined,req);res.json({success:true,data:o})}catch(e){next(e)}});

app.post('/api/v1/p2p/orders/:id/release',auth,async(req:AuthReq,res,next)=>{try{const order=await prisma.p2POrder.findUnique({where:{id:(req.params.id as string)},include:{escrow:true}});if(!order||order.sellerId!==req.auth!.id)return res.status(404).json({success:false,code:'ORDER_NOT_FOUND'});if(order.status!==P2PStatus.PAYMENT_SENT||!order.escrow)return res.status(409).json({success:false,code:'ESCROW_NOT_RELEASEABLE'});const result=await prisma.$transaction(async tx=>{await tx.escrow.update({where:{id:order.escrow!.id},data:{releasedAt:new Date()}});return tx.p2POrder.update({where:{id:order.id},data:{status:P2PStatus.COMPLETED}})});await audit(req.auth!.id,'P2P_ESCROW_RELEASED','P2POrder',result.id,'Seller confirmed fiat receipt',req);res.json({success:true,data:result})}catch(e){next(e)}});

app.post('/api/v1/p2p/orders/:id/dispute',auth,async(req:AuthReq,res,next)=>{try{const input=z.object({reason:z.string().min(10).max(2000)}).parse(req.body);const order=await prisma.p2POrder.findUnique({where:{id:(req.params.id as string)}});if(!order||![order.buyerId,order.sellerId].includes(req.auth!.id))return res.status(404).json({success:false,code:'ORDER_NOT_FOUND'});const d=await prisma.$transaction(async tx=>{const dispute=await tx.dispute.create({data:{orderId:order.id,openedBy:req.auth!.id,reason:input.reason}});await tx.p2POrder.update({where:{id:order.id},data:{status:P2PStatus.DISPUTED}});return dispute});await audit(req.auth!.id,'P2P_DISPUTE_OPENED','Dispute',d.id,input.reason,req);res.status(201).json({success:true,data:d})}catch(e){next(e)}});

app.use((err:unknown,_req:express.Request,res:express.Response,_next:express.NextFunction)=>{if(err instanceof z.ZodError) return res.status(400).json({success:false,code:'VALIDATION_ERROR',issues:err.issues.map(i=>({path:i.path.join('.'),message:i.message}))});console.error(err);res.status(500).json({success:false,code:'INTERNAL_ERROR',message:'An unexpected error occurred'})});
export default app;
if(!process.env.VERCEL){const port=Number(process.env.PORT??4000);app.listen(port,()=>console.log(`SecureTrade API listening on :${port}`));}
